### ISSUE TITLE
Minor (new) bug in Craft 2 version

### ISSUE THREAD

**Issue by lindseydiloreto** [ttempleton/craft-nocache#18]
I know you're probably barely supporting the Craft 2 version, but just wanted to let you know that a **brand new** bug has been introduced by a recent version of Craft 2.

```
Fatal error: Uncaught TypeError: Argument 1 passed to __NoCacheTemplate_okg3IDPFLZ6ciU7ZHH8N0N6H::__construct() must be an instance of Environment, instance of Craft\TwigEnvironment given, called in /.../craft/plugins/nocache/services/NoCacheService.php on line 98 and defined in /.../craft/storage/runtime/compiled_templates/nocache/nocache_okg3IDPFLZ6ciU7ZHH8N0N6H.php:6

Stack trace:
#0 /.../craft/plugins/nocache/services/NoCacheService.php(98): __NoCacheTemplate_okg3IDPFLZ6ciU7ZHH8N0N6H->__construct(Object(Craft\TwigEnvironment))
#1 /.../craft/plugins/nocache/NoCachePlugin.php(116): Craft\NoCacheService->render('okg3IDPFLZ6ciU7...', 'xwy4NJxt')
#2 [internal function]: Craft\NoCachePlugin->Craft\{closure}(Array)
#3 /.../craft/plugins/nocache/NoCachePlugin.php(123): preg_replace_callback('/<no-cache>([a-...', Object(Closure), '<!doctype html>...')
#4 [ in /.../craft/storage/runtime/compiled_templates/nocache/nocache_okg3IDPFLZ6ciU7ZHH8N0N6H.php on line 6
```

I'll try to hack the plugin in the meantime.

### Additional information
- No-Cache version: 1.0.3
- Craft CMS version: 2.7.10

**Comment by lindseydiloreto** [comment]
Alright, it's possible that it's not a "brand new" bug, but it's certainly new to me. 🙂 

My suspicion is that it was introduced in Craft `2.7.7`. 

>Updated Twig to 1.38.4.

https://github.com/craftcms/cms/blob/master-v2/CHANGELOG-v2.md#277---2019-03-23

The issue definitely cropped up when we updated from Craft `2.7.5` --> `2.7.10`

**Comment by ttempleton** [comment]
Hi @lindseydiloreto,

"Barely supporting the Craft 2 version" is probably a good description at this point 😄.  It's unlikely that I'll make any official releases of the Craft 2 version (mainly because I don't want to replace @benjamminf's name as developer of the Craft 2 version), but if any compatibility issues occur with new releases of Craft 2, I'll still fix those in the [`craft-2`](https://github.com/ttempleton/craft-nocache/tree/craft-2) branch.

In any case, this sounds like issue #13, which should have been fixed in the most recent update to the `craft-2` branch.  If so, then replacing the old `nocache/twigextensions/NoCache_Node_Module.php` with [the updated version](https://raw.githubusercontent.com/ttempleton/craft-nocache/craft-2/nocache/twigextensions/NoCache_Node_Module.php) should fix the error (and please let me know if it doesn't!)

**Comment by lindseydiloreto** [comment]
Ah yes, that other thread describes the problem perfectly!

Thanks @ttempleton, sorry for double-posting! 🍺
