### ISSUE TITLE
<no-cache> cached

### ISSUE THREAD

**Issue by extensibleseth** [ttempleton/craft-nocache#20]
### Description
With HTML Cache enabled, even with none of it's option enabled, 

> {% nocache %}{{ getCsrfInput() }}{% endnocache %}

renders correctly the first time, but as:

> <no-cache>3HkJuIQdEFS4Rvv50KnpVs3s-fIhF5j7S</no-cache>

on all subsequent page loads. With HTML Cache disabled the form works fine.

### Additional information
No-Cache version: Latest craft-2 commit.
Craft CMS version: 2.8.0.1
PHP version: 7.2.24
Also using HTML Cache 1.0.4.1

**Comment by ttempleton** [comment]
Could you please double-check HTML Cache's settings and confirm that the UberCache setting is definitely disabled when this happens?  I can only reproduce this behaviour with UberCache enabled (an incompatibility between the plugins which unfortunately can't be resolved, because UberCache bypasses Craft, and therefore also No-Cache, when it finds the HTML file to load).

**Comment by ttempleton** [comment]
I'll close this issue now, due to the issue not being reproducible with none of HTML Cache's settings enabled, and the lack of feedback regarding the UberCache setting.

To better explain the incompatibility between No-Cache and UberCache, though: Enabling UberCache modifies a website's `public/index.php` to execute HTML Cache functionality *before* Craft, but No-Cache intercepts Craft's output to replace `<no-cache>` tags with their content, which No-Cache can't do if the request is essentially bypassing Craft.
