### ISSUE TITLE
Issue with PHP OPCache?

### ISSUE THREAD

**Issue by roberttolton** [ttempleton/craft-nocache#6]
I've had issues where, in production running OPCache, I've cleared the template cache from the Admin Control Panel, gone back to the front-end of the site and my no-cache blocks are completely empty and breaking quite a lot of the site.

This is only cleared by restarting PHP, thus restarting OPCache.

Is this something you're aware of, or know a better way of dealing with clearing template caches with OPCache enabled?

**Comment by robstrover-fuel** [comment]
I am also having this problem. Anyone got a solution?

**Comment by ttempleton** [comment]
@roberttolton, @robstrover-fuel, sorry for not addressing this sooner.  I've been testing with OPcache and No-Cache (both Craft 2 and Craft 3 versions) and unfortunately have yet to reproduce this issue.  I'm wondering if any OPcache settings could cause problems, though.  If either of you continue to use Craft 2 with No-Cache (or have upgraded to the Craft 3 version) and still experience this issue, could you please let me know what OPcache settings you use?

**Comment by kishalmi** [comment]
quite a similar issue here. when clearing our craft 3 compiled template caches, all the no-cached blocks (forms, mainly for their CSRF tokens) were gone.

opcache settings: `grep opcache php.ini`
```[opcache]
opcache.enable = 1
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 64
opcache.max_accelerated_files = 30000
opcache.validate_timestamps = 0
opcache.save_comments = 1```
(i removed the ;commented lines)

**Comment by ttempleton** [comment]
Hi @kishalmi,

Did you experience this after clearing both the compiled templates and the template caches, or just the compiled templates?  There are issues with No-Cache blocks when clearing compiled templates but not template caches; this happens because No-Cache compiled template IDs are randomised, so the generated `<no-cache>` tag in the cached template will be pointing to a No-Cache compiled template that no longer exists.  I definitely plan to look into how that could be resolved (hopefully it can be, given Craft itself seems to have no issues with clearing its compiled templates without clearing the template caches), but in the meantime, you'd need to also clear the template caches (and if that still doesn't work, please let me know!)

I don't believe that issue is related to OPcache, though, as it seems to happen to me in all cases.

**Comment by kishalmi** [comment]
thanks @ttempleton,

I can confirm that clearing compiled templates reliably breaks one of our forms.
(the one inside a matrix-field)
clearing template caches afterwards indeed solves the issue.

no idea why the other form keeps working, 
(embedded rather plainly inside a page template) 
even after clearing compiled templates.
it might well have a static CSRF token though, 
effectively breaking submission... needs more debugging.

looking forward to a robust solution in future releases!

**Comment by ttempleton** [comment]
@kishalmi I believe I have found a good solution to that issue; update to No-Cache v2.0.6 and please let me know if that has resolved the issue for you!

**Comment by ttempleton** [comment]
Closing this issue now, as it seems the OPcache issue isn't reproducible.  If @roberttolton, @robstrover-fuel or anyone else has more information on any incompatibility with OPcache, please let me know and I'll reopen this issue.  @kishalmi, if you continue to experience issues when clearing compiled templates but not template caches, please feel free to open a new issue.
